import { Location } from '@/types';

// ANKARA LOKASYONLARı - Kızılay merkez (39.9208, 32.8541)
export const ankaraLocations: Location[] = [
  // Kafeler & Restoranlar (Gerçek konumlar)
  {
    id: 'ank-1',
    name: 'Kızılay Kahve Diyarı',
    category: 'cafe',
    coordinates: [39.9208, 32.8541],
    address: 'Kızılay Meydanı No:5, Çankaya, Ankara',
    currentCrowdLevel: 'high',
    averageWaitTime: 8,
    lastUpdated: new Date(),
    description: 'Kızılay meydanında merkezi lokasyon',
  },
  {
    id: 'ank-2',
    name: 'Tunalı Keyif Kahve',
    category: 'cafe',
    coordinates: [39.9168, 32.8573],
    address: 'Tunalı Hilmi Caddesi No:112, Kavaklıdere, Çankaya',
    currentCrowdLevel: 'moderate',
    averageWaitTime: 5,
    lastUpdated: new Date(),
    description: 'Tunalı\'nın en popüler kahvelerinden',
  },
  {
    id: 'ank-3',
    name: 'Armada Bahçe Cafe',
    category: 'cafe',
    coordinates: [39.9195, 32.8623],
    address: 'Armada İş Merkezi Kat:1, Söğütözü, Çankaya',
    currentCrowdLevel: 'low',
    averageWaitTime: 3,
    lastUpdated: new Date(),
    description: 'Armada\'da sakin ortam',
  },
  
  // Bankalar (Gerçek şubeler)
  {
    id: 'ank-4',
    name: 'Garanti BBVA Kızılay Şubesi',
    category: 'bank',
    coordinates: [39.9198, 32.8538],
    address: 'Atatürk Bulvarı No:87, Kızılay, Çankaya',
    currentCrowdLevel: 'very_high',
    averageWaitTime: 25,
    lastUpdated: new Date(),
    description: 'Merkez şube - Yoğun',
  },
  {
    id: 'ank-5',
    name: 'Türkiye İş Bankası Kavaklıdere Şubesi',
    category: 'bank',
    coordinates: [39.9178, 32.8565],
    address: 'Tunalı Hilmi Caddesi No:98, Kavaklıdere, Çankaya',
    currentCrowdLevel: 'high',
    averageWaitTime: 18,
    lastUpdated: new Date(),
    description: 'Kurumsal işlemler için ideal',
  },
  {
    id: 'ank-6',
    name: 'Yapı Kredi Bankası Kızılay Şubesi',
    category: 'bank',
    coordinates: [39.9215, 32.8548],
    address: 'Ziya Gökalp Caddesi No:45, Kızılay, Çankaya',
    currentCrowdLevel: 'moderate',
    averageWaitTime: 12,
    lastUpdated: new Date(),
    description: 'Geniş şube',
  },
  {
    id: 'ank-7',
    name: 'Ziraat Bankası Ulus Şubesi',
    category: 'bank',
    coordinates: [39.9420, 32.8597],
    address: 'Ulus Meydanı No:12, Ulus, Altındağ',
    currentCrowdLevel: 'high',
    averageWaitTime: 22,
    lastUpdated: new Date(),
    description: 'Tarihi şube',
  },
  
  // Hastaneler
  {
    id: 'ank-8',
    name: 'Ankara Numune Eğitim ve Araştırma Hastanesi',
    category: 'hospital',
    coordinates: [39.9324, 32.8632],
    address: 'Altındağ, Ankara',
    currentCrowdLevel: 'very_high',
    averageWaitTime: 60,
    lastUpdated: new Date(),
    description: 'Acil servis',
  },
  {
    id: 'ank-9',
    name: 'Ankara Şehir Hastanesi',
    category: 'hospital',
    coordinates: [39.9485, 32.7268],
    address: 'Bilkent, Çankaya',
    currentCrowdLevel: 'high',
    averageWaitTime: 45,
    lastUpdated: new Date(),
    description: 'Kampüs hastane',
  },
  {
    id: 'ank-10',
    name: 'Özel Sağlık Merkezi',
    category: 'hospital',
    coordinates: [39.8782, 32.7611],
    address: 'Söğütözü, Çankaya',
    currentCrowdLevel: 'moderate',
    averageWaitTime: 30,
    lastUpdated: new Date(),
    description: 'Özel hastane',
  },
  
  // Noterler (Gerçek noterlikler)
  {
    id: 'ank-11',
    name: 'Çankaya 1. Noteri',
    category: 'notary',
    coordinates: [39.9188, 32.8558],
    address: 'Tunalı Hilmi Caddesi No:76/3, Kavaklıdere, Çankaya',
    currentCrowdLevel: 'high',
    averageWaitTime: 35,
    lastUpdated: new Date(),
    description: 'Tapu ve sözleşme işlemleri',
  },
  {
    id: 'ank-12',
    name: 'Çankaya 5. Noteri',
    category: 'notary',
    coordinates: [39.9218, 32.8535],
    address: 'Meşrutiyet Caddesi No:34, Kızılay, Çankaya',
    currentCrowdLevel: 'very_high',
    averageWaitTime: 42,
    lastUpdated: new Date(),
    description: 'Yoğun noter - Randevu önerilir',
  },
  
  // Eczaneler (Gerçek eczaneler)
  {
    id: 'ank-13',
    name: 'Kızılay Çağdaş Eczanesi',
    category: 'pharmacy',
    coordinates: [39.9205, 32.8545],
    address: 'Kızılay Meydanı No:18, Kızılay, Çankaya',
    currentCrowdLevel: 'moderate',
    averageWaitTime: 4,
    lastUpdated: new Date(),
    description: '7/24 Nöbetçi Eczane - İlaç temini garantili',
  },
  {
    id: 'ank-14',
    name: 'Tunalı Sağlık Eczanesi',
    category: 'pharmacy',
    coordinates: [39.9175, 32.8570],
    address: 'Tunalı Hilmi Caddesi No:124, Kavaklıdere, Çankaya',
    currentCrowdLevel: 'low',
    averageWaitTime: 2,
    lastUpdated: new Date(),
    description: 'Geniş ilaç çeşitliliği',
  },
  
  // Alışveriş Merkezleri
  {
    id: 'ank-15',
    name: 'Ankamall AVM',
    category: 'shopping',
    coordinates: [39.9625, 32.7368],
    address: 'Akköprü, Etimesgut',
    currentCrowdLevel: 'very_high',
    averageWaitTime: 0,
    lastUpdated: new Date(),
    description: 'Ankara\'nın en büyük AVM\'si',
  },
  {
    id: 'ank-16',
    name: 'Armada AVM',
    category: 'shopping',
    coordinates: [39.9195, 32.8623],
    address: 'Söğütözü, Çankaya',
    currentCrowdLevel: 'high',
    averageWaitTime: 0,
    lastUpdated: new Date(),
    description: 'Merkezi konumda',
  },
  {
    id: 'ank-17',
    name: 'Panora AVM',
    category: 'shopping',
    coordinates: [39.9135, 32.8012],
    address: 'Oran, Çankaya',
    currentCrowdLevel: 'moderate',
    averageWaitTime: 0,
    lastUpdated: new Date(),
  },
  
  // Kamu Kurumları (Gerçek kurumlar)
  {
    id: 'ank-18',
    name: 'Çankaya Belediyesi Hizmet Binası',
    category: 'public',
    coordinates: [39.9172, 32.8612],
    address: 'Balgat Mahallesi, Çetin Emeç Bulvarı, Çankaya',
    currentCrowdLevel: 'high',
    averageWaitTime: 32,
    lastUpdated: new Date(),
    description: 'Belediye hizmetleri',
  },
  {
    id: 'ank-19',
    name: 'Çankaya Nüfus Müdürlüğü',
    category: 'public',
    coordinates: [39.9195, 32.8525],
    address: 'Necatibey Caddesi No:56, Kızılay, Çankaya',
    currentCrowdLevel: 'very_high',
    averageWaitTime: 38,
    lastUpdated: new Date(),
    description: 'Nüfus işlemleri - E-randevu önerilir',
  },
  
  // Ulaşım
  {
    id: 'ank-20',
    name: 'Kızılay Metro İstasyonu',
    category: 'transport',
    coordinates: [39.9208, 32.8541],
    address: 'Kızılay Meydanı',
    currentCrowdLevel: 'very_high',
    averageWaitTime: 0,
    lastUpdated: new Date(),
    description: 'Ana aktarma noktası',
  },
  {
    id: 'ank-21',
    name: 'AŞTI (Otobüs Terminali)',
    category: 'transport',
    coordinates: [39.9515, 32.8048],
    address: 'Şentepe, Yenimahalle',
    currentCrowdLevel: 'high',
    averageWaitTime: 0,
    lastUpdated: new Date(),
    description: 'Şehirlerarası otobüs',
  },
  
  // Eğlence
  {
    id: 'ank-22',
    name: 'Armada Sinemaları',
    category: 'entertainment',
    coordinates: [39.9190, 32.8615],
    address: 'Armada AVM',
    currentCrowdLevel: 'moderate',
    averageWaitTime: 10,
    lastUpdated: new Date(),
  },
  {
    id: 'ank-23',
    name: 'Kültür Merkezi Etkinlik Salonu',
    category: 'entertainment',
    coordinates: [39.9156, 32.8632],
    address: 'Aydınlıkevler, Çankaya',
    currentCrowdLevel: 'low',
    averageWaitTime: 0,
    lastUpdated: new Date(),
  },
  
  // Parklar
  {
    id: 'ank-24',
    name: 'Kuğulu Park',
    category: 'park',
    coordinates: [39.9145, 32.8598],
    address: 'Gaziosmanpaşa, Çankaya',
    currentCrowdLevel: 'moderate',
    averageWaitTime: 0,
    lastUpdated: new Date(),
    description: 'Kuğularıyla ünlü park',
  },
  {
    id: 'ank-25',
    name: 'Gençlik Parkı',
    category: 'park',
    coordinates: [39.9315, 32.8485],
    address: 'Ulus, Altındağ',
    currentCrowdLevel: 'low',
    averageWaitTime: 0,
    lastUpdated: new Date(),
    description: 'Tarihi park',
  },
  {
    id: 'ank-26',
    name: 'Seğmenler Parkı',
    category: 'park',
    coordinates: [39.9265, 32.8425],
    address: 'Seğmenler, Çankaya',
    currentCrowdLevel: 'low',
    averageWaitTime: 0,
    lastUpdated: new Date(),
  },
  
  // Spor Salonları
  {
    id: 'ank-27',
    name: 'Form Spor Salonu Kızılay',
    category: 'gym',
    coordinates: [39.9195, 32.8555],
    address: 'Kızılay, Çankaya',
    currentCrowdLevel: 'high',
    averageWaitTime: 0,
    lastUpdated: new Date(),
    description: 'Modern fitness merkezi',
  },
  {
    id: 'ank-28',
    name: 'Aktif Yaşam Spor Merkezi',
    category: 'gym',
    coordinates: [39.9170, 32.8575],
    address: 'Tunalı Hilmi',
    currentCrowdLevel: 'moderate',
    averageWaitTime: 0,
    lastUpdated: new Date(),
  },
  
  // Marketler (Gerçek marketler)
  {
    id: 'ank-29',
    name: 'Migros 5M Kızılay',
    category: 'market',
    coordinates: [39.9202, 32.8548],
    address: 'İzmir Caddesi No:23, Kızılay, Çankaya',
    currentCrowdLevel: 'very_high',
    averageWaitTime: 8,
    lastUpdated: new Date(),
    description: 'Geniş ürün yelpazesi',
  },
  {
    id: 'ank-30',
    name: 'CarrefourSA Tunalı Express',
    category: 'market',
    coordinates: [39.9168, 32.8568],
    address: 'Tunalı Hilmi Caddesi No:104, Kavaklıdere, Çankaya',
    currentCrowdLevel: 'high',
    averageWaitTime: 6,
    lastUpdated: new Date(),
    description: 'Hızlı alışveriş',
  },
  {
    id: 'ank-31',
    name: 'A101 Çankaya Şubesi',
    category: 'market',
    coordinates: [39.9185, 32.8595],
    address: 'Kültür Mahallesi, Çankaya',
    currentCrowdLevel: 'moderate',
    averageWaitTime: 4,
    lastUpdated: new Date(),
    description: 'Uygun fiyatlı market',
  },
];

// Şehir merkezleri
export const cityConfig = {
  ankara: {
    name: 'Ankara',
    center: [39.9208, 32.8541] as [number, number], // Kızılay
    zoom: 13,
    locations: ankaraLocations,
  },
  istanbul: {
    name: 'İstanbul',
    center: [41.0082, 28.9784] as [number, number], // Taksim
    zoom: 13,
    locations: [], // İstanbul lokasyonları buraya eklenecek
  },
};

export const defaultCity = 'ankara'; // Varsayılan şehir Ankara
